### ISSUE TITLE
Bug Report: Shared Conversations Accessible Without Login

### ISSUE THREAD

**Issue by nhutnguyenhong** [huggingface/chat-ui#1502]
## Bug description

While shared conversations require a login, it is currently possible to access the content of a shared conversation without logging in by deleting the login popup's DIV element in the HTML code.

## Steps to reproduce

Visit a shared conversation.
Inspect the HTML code of the page (right-click and select "Inspect" or "Inspect Element").
Locate the login popup's DIV element in the HTML code.
Delete the DIV element.

Expected Result: The conversation content should be completely hidden and users should be required to log in.

Impact: This issue allows unauthorized users to access sensitive conversation data, potentially compromising privacy.

**Comment by nsarrazin** [comment]
Hi! I think if I understand correctly this is expected behaviour, we want conversations to be shareable to people without an account, at least on HuggingChat. 

So you shouldn't see the modal at all in that case, I think that's a bug.

Would you be interested in this behavior being configurable ? (a flag so that only logged in users can see shared conversations)

**Comment by nhutnguyenhong** [comment]
You're right, @nsarrazin, now I understand the intention of "share" feature is to allow public access to shared conversations on HuggingChat. However, I think it would be valuable to have the ability to configure this behavior for different contexts.

A flag that allows us to restrict shared conversations to logged-in users within the same organization would give us greater control over data visibility and security. This would be particularly useful for sensitive or confidential conversations.

Thanks.
