### ISSUE TITLE
Facing Error 403 after deployment

### ISSUE THREAD

**Issue by awsum0225** [huggingface/chat-ui#364]
Hi folks!
My Chat-UI setup along with a custom LangChain model works perfect on localhost. I tried to deploy it on an Azure VM with Docker Containers and I have been facing this issue which might be due to MongoDB.

![image](https://github.com/huggingface/chat-ui/assets/39643649/82b75337-7e99-4347-82ab-1ab4a1a38f93)

 Any help is appreciated. Thank you

**Comment by nsarrazin** [comment]
Mmh that's strange. It could be due to cookies, do you have anything going on there with your browser ?

**Comment by awsum0225** [comment]
@nsarrazin Hey! I cleared the cookies and tried, the issue persist. Also I tried to deploy it on 2 separate VMs and faced the same issue. I sense it could be due to MongoDB config. Is there any other configuration that we need to change while deploying to production?
Thanks.

**Comment by awsum0225** [comment]
After some digging I found out this to be an authentication issue, I managed to fetch the conversation with a tweak mentioned in #330 `RUN find /app/src/routes/conversation/ -type f | xargs sed -i 's/...authCondition(locals),/\/\/ ...authCondition(locals),/g'`

Now when I'm running the build, the response received from text-generation-inference loads in the same div as of the message sent by user:
![image](https://github.com/huggingface/chat-ui/assets/39643649/0aa291a9-c362-4281-ae2a-55ed212d1429)
and when I refresh the window it then loads normally:
![image](https://github.com/huggingface/chat-ui/assets/39643649/0ca4019c-a835-4ee8-b5bc-9c663b620efe)

This works perfect in `npm run build` but not in `node build`

@nsarrazin Hope you could help me out on this. Thanks

**Comment by StephennFernandes** [comment]
@awsum0225 hey incase you don't mind, could you please tell how did you integrate langchain to work with chat ui ? link to some references would also help. Thanks

**Comment by awsum0225** [comment]
> @awsum0225 hey incase you don't mind, could you please tell how did you integrate langchain to work with chat ui ? link to some references would also help. Thanks

You can refer to my previous issue #295

**Comment by EikeKohl** [comment]
I am encountering the same issue and I found that it has indeed to do with the `authCondition(locals)` call. After implementing some debugging steps, I noticed, that my sessionId changes whenever I access another path in the chat UI url. This typically happens if you try to enter a message into the chat, because "conversations/CONVERSATION_ID" will be appended:

![image](https://github.com/huggingface/chat-ui/assets/57795397/dab15970-c3ed-49f6-ae36-f0e0fc8dec53)

The item in the mongodb that is being created looks as follows:
```JSON
[
	{
		"_id": "64eb476f7dab069373ba9145",
		"title": "Untitled 1",
		"messages": [],
		"model": "OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5",
		"createdAt": "2023-08-27T12:54:07.043Z",
		"updatedAt": "2023-08-27T12:54:07.043Z",
		"sessionId": "df7c6134-9aae-4de0-8793-13fb1fa3e676"
	}
]
```
The load function in src/routes/conversation/[id]/page.server.ts calls the `authCondition(locals)` function and filters the conversations in the mongodb using the sessionId if you do not use user login:

```typescript
export const authCondition = (locals: App.Locals) => {
	return locals.user
		? { userId: locals.user._id }
		: { sessionId: locals.sessionId, userId: { $exists: false } };
};
```

```typescript
	const conversation = await collections.conversations.findOne({
		_id: new ObjectId(params.id),
		...authCondition(locals),
	});
```
**However**, this call already returns another sessionId "06ace6bc-cf54-45dc-86a6-bf0a4dc9d03c", thus returning no object as the conversation constant. The if statement below is true, and the `conversationExists `check runs and returns true, therefore throwing the 403 error:

```typescript
if (!conversation) {
const conversationExists =
	(await collections.conversations.countDocuments({
		_id: new ObjectId(params.id),
	})) !== 0;

if (conversationExists) {
	throw error(
		403,
		"You don't have access to this conversation. If someone gave you this link, ask them to use the 'share' feature instead."
			);
		}
```
Since this does not occur when I run both the mongodb and the huggingface chatui as docker containers locally, I assume it has to do with how cookies are being set in my deployment. I used AWS ECS to run the docker container on Fargate and the application has a load balancer which might cause sessionIds to change whenever new paths are called in the huggingface chatui. I have no clean solution yet, but I am working on it. I assume that using the login / user feature might help, because the conversation is not being retrieved using the sessionId. I will try that and give an update.
@awsum0225 Do you think that this might also be the reason for your problems?

**Comment by EikeKohl** [comment]
Update:

I removed all the load balancing and the issue persisted. Another idea what might be the problem is HTTP vs. HTTPS. Maybe the application needs to run on HTTPS in order for the cookies to work correctly. I notices, that the sessionId cookie seems to simply not be saved and gets regenerated everytime in `src/hooks.server.ts`:

```typescript
	const token = event.cookies.get(COOKIE_NAME);

	event.locals.sessionId = token || crypto.randomUUID();
```

I just set the sessionId to a fixed value. That way at least the conversation history is displayed (all users will ahve the same conversation history though):

```typescript
	const token = event.cookies.get(COOKIE_NAME);

	event.locals.sessionId = token || 42;
```

**Comment by mbuet2ner** [comment]
@EikeKohl check https://github.com/huggingface/chat-ui/issues/330#issuecomment-1620954007 (as pointed out earlier): seems indeed to be a HTTPS thing. booday also mentions it [in his repository](https://github.com/bodaay/HuggingChatAllInOne#to-run). 

Copied from there:
> You need to set APPLY_PATCHES in the following cases for PUBLIC_ORIGIN:
>- you are not running this in https://runpod.io/, or a secure https connection
>- you need to access this site using ip address or non secure domain name (not http://localhost:8080/), ex: http://10.0.0.1:8080/, http://example.com/

For the `session_id` and the AWS Application Load Balancer: maybe [this](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/sticky-sessions.html) helps?

**Comment by EikeKohl** [comment]
Load balancer stickiness did not seem to work for HTTP. I just implemented HTTPS directly and now it works.

**Comment by majestichou** [comment]
> Maybe this helps someone: I recently wrote a [blog post](https://www.inovex.de/de/blog/code-assistant-how-to-self-host-your-own/) about self-hosting ChatUI + TGI via `docker-compose`– with SSL via a nginx reverse proxy. The files are available from [here](https://github.com/inovex/blog-code-assistant) 🙂.
I used your method and it did solve the 403 problem. But then, there was another problem. The first problem is that the output of the large model is no longer streamed, but segment by segment, and the text appears segment by segment. The second problem is that large models can only answer one question. After the big model answers the first question, I enter the second question in the input box and press Enter. An error is reported. The error information is:
```
chat-ui  | Error: Ancestor not found
chat-ui  |     at file:///app/.svelte-kit/output/server/chunks/buildSubtree.js:20:17
chat-ui  |     at Array.map (<anonymous>)
chat-ui  |     at buildSubtree (file:///app/.svelte-kit/output/server/chunks/buildSubtree.js:17:29)
chat-ui  |     at POST (file:///app/.svelte-kit/output/server/entries/endpoints/conversation/_id_/_server.ts.js:563:25)
chat-ui  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
chat-ui  |     at async render_endpoint (file:///app/.svelte-kit/output/server/index.js:223:20)
chat-ui  |     at async resolve (file:///app/.svelte-kit/output/server/index.js:2667:22)
chat-ui  |     at async Object.handle (file:///app/.svelte-kit/output/server/chunks/hooks.server.js:88:20)
chat-ui  |     at async respond (file:///app/.svelte-kit/output/server/index.js:2556:22)
chat-ui  |     at async file:///app/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js:171:5
nginx    | 56.40.x.abc - - [29/Feb/2024:19:54:15 +0000] "POST /conversation/65e0e0baebd0782222027d61 HTTP/1.1" 500 28 "https://56.40.e.bef/conversation/65e0e0baebd0782222027d61" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
nginx    | 56.40.x.abc - - [29/Feb/2024:19:54:15 +0000] "GET /conversation/65e0e0baebd0782222027d61/__data.json?x-sveltekit-invalidated=10 HTTP/1.1" 200 920 "https://56.40.e.bef/conversation/65e0e0baebd0782222027d61" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
```

**Comment by nsarrazin** [comment]
I recently added a feature flag for disabling the secure cookie check. Make sure to add `ALLOW_INSECURE_COOKIES=true` to your .env.local and the issue should be fixed!
