### ISSUE TITLE
Features request - Add Zephyr 7B Alpha to hugging chat

### ISSUE THREAD

**Issue by julien-blanchon** [huggingface/chat-ui#500]
https://huggingface.co/HuggingFaceH4/zephyr-7b-alpha

https://x.com/huggingface/status/1711780979574976661?s=46&t=OG912HgMe3THDQku9H2fSA

What are you thinking about adding zephyr to the public huggingface instance ?

**Comment by nsarrazin** [comment]
[Their demo](https://huggingface.co/spaces/HuggingFaceH4/zephyr-chat) actually uses chat-ui :grin: 

But not sure about adding it to huggingchat. 

I think with the reworked settings/presets  it would be really cool to support a wide variety of models so that people can create presets for many models on the hub. (cc @gary149)

But with the current UI I think we're kind of limited in the number of models we can easily show before it gets confusing and we already have mistral 7B... maybe @osanseviero has thoughts on this ?

**Comment by gary149** [comment]
IMO it's fine to keep it in it's own Space for now (and focus more on base models on HuggingChat).

**Comment by julien-blanchon** [comment]
I understand that having to many model could be confusing. To my experience it's the best open source model available to date, so even this could be good so showcase it in the public instance.

Let's see how thing evolve, I'm closing the issue to avoid spam
