### ISSUE TITLE
Custom Theme

### ISSUE THREAD

**Issue by kaplanyaniv** [huggingface/chat-ui#546]
I want to change the UI layout yet still be able to update the code in order to enjoy the new features as they are released.
Is there a way to add my changes in a way that would be similar to a theme? or an outside addon?

**Comment by julien-blanchon** [comment]
By adjusting the settings in `tailwind.config.cjs` (details at https://tailwindcss.com/docs/theme), you have the capability to perform a multitude of tasks. Since this customization is consolidated into a single file, it simplifies the process of updating your local version while preserving any personalized configurations you've made in your `tailwind.config.cjs`. If necessary, we could consider further customization options for the user interface beyond the `PUBLIC_APP_COLOR`. What does your configuration look like?

**Comment by nsarrazin** [comment]
I think @julien-blanchon answered this quite well, I'm closing this for now, let me know if you need any more help and I'll reopen!
