### ISSUE TITLE
Error "fetch failed" sometimes during web search

### ISSUE THREAD

**Issue by mishig25** [huggingface/chat-ui#691]
Sometimes websearch gives you an error "fetch failed". The error is happening when websearch was succesfull, but the RAG augmented message generation failed

And error log in server shows
>  cause: SocketError: other side closed

I wasn't able to reproduce the error locally. However, will spend more time & fix this error

**Comment by flurb18** [comment]
I have this error. How do I enable increased verbosity? With `npm run dev`, there are no errors serverside nor in the browser console. Furthermore, I have hosted my own text-embeddings-inference endpoint at an address and port which I have verified chat-ui can access, and the error persists. Using the following .env.local:

`...
TEXT_EMBEDDING_MODELS=`[
  {
    "name": "intfloat/e5-large-v2",
    "displayName": "intfloat/e5-large-v2",
    "description": "hosted embedding model",
    "chunkCharLength": 512,
    "preQuery": "query: ",
    "prePassage": "passage: ",
    "endpoints": [
      {
        "type": "tei",
        "url": "http://embeddings:80"
      }
    ]
  }
]
`
I am using docker; I have a chat-ui container, and an embeddings container. This should work; earlier in my .env.local I have
`MODELS=`[
  {
    "name": "text-generation-webui",
    "id": "text-generation-webui",
    "parameters": {
      "temperature": 0.7,
      "truncate": 16384,
      "max_new_tokens": 2048,
      "stop": []
    },
    "endpoints": [{
      "type" : "openai",
      "baseURL": "http://textgen:5000/v1"
    }]
  }
]`
`
with text-generation-webui running in a docker container named textgen, which works for the text generation endpoint.
Even when I change 'url' in TEXT_EMBEDDING_MODELS to the machine's address on my VPN and forward the port I still get fetch failed. Could it be an issue with plain http instead of https?

**Comment by mishig25** [comment]
Opening the issue back until it is fully tested in prod

**Comment by mishig25** [comment]
this error is fixed. It was some load balancing issue in the cloud

**Comment by dmauas** [comment]
Happens constantly. Chat is usable 1 out of 30 times I try it.
