### ISSUE TITLE
Popular Assistants page not working locally

### ISSUE THREAD

**Issue by gururise** [huggingface/chat-ui#768]
I'm playing around with the new assistants features locally and I've created several assistants; however, the popular assistants page always shows "**No assistants found**"
![image](https://github.com/huggingface/chat-ui/assets/4380009/743e6607-913a-4771-b24f-7d79575b7622)

I have created six assistants, but none of them show up under the popular assistants page:
![image](https://github.com/huggingface/chat-ui/assets/4380009/73cd1ff9-5f75-457a-8606-e9c89f642694)

**Comment by nsarrazin** [comment]
Hi! I think it's because we added at the last minute [a check](https://github.com/huggingface/chat-ui/blob/main/src/routes/assistants/%2Bpage.server.ts#L16) for a `featured` field in the assistant document in the DB when querying assistants.

I'll be adding an env variable for controlling that soon, or you can also open a PR for it if you feel like it :grin:
