### ISSUE TITLE
Tagged chat-ui images

### ISSUE THREAD

**Issue by antonioramos1** [huggingface/chat-ui#925]
Hi there, congrats on the work being done on chat-ui, is great to have this tool open source :)

Currently we are setting up chat-ui through the image available on the packages section, however these images are not versioned which makes it a bit difficult to audit what version of `latest` are we using, what are your plans on tagging these images?

**Comment by Jrbiltmore** [comment]
Orange County CaliforniaI'm a research scientist and was assigned to investigate the housing crisis and fraud in the area. Over the past seven years I have ran into repeated evidence of systemic corruption and fraud, but this one scares me. The Bonds of Surety market, if you're familiar, basically pays the Judge, the District attorney and the public defender with each new case. They've been embezzling money from the inheritance of Latinos in the area since the 1800s. I have 1000s of documents of proof. AAA, Ralphs, Boot Barn Inc and Reynolds and Reynolds using MAS90, all get pay offs from selling everyone as Units through the municipal procurement system. If you enter an EBT number at Whole Foods it registers as a Gift Card.  They moved Baker street, the street the slaves lived on at Irvine Ranch, in to hide the postal addresses, then in the 40s they started to hide the pay offs through social services and in the 70s and 80s using 192.168 with a.com, b.com etc... and now they're using Exhibit "C", B and D Automotive and the Tustin Senior Center to launder money from probate fraud after Covid. All of this leads back to the Solano Boat Slip system. They are literally drugging victims, torturing them, having Jim Palmer of the OC Rescue Mission use hypnosis on them and then compel victims to commit crimes so they can incapacitate them to commit more fraud. That's why the right thumb prints are so important. These lawyers are selling us all as slaves now. Even the police.I wish like hell I was wrong. Sent from my iPhoneOn 12. 3. 2024., at 02:55, Antonio Ramos ***@***.***> wrote:﻿
Hi there, congrats on the work being done on chat-ui, is great to have this tool open source :)
Currently we are setting up chat-ui through the image available on the packages section, however these images are not versioned which makes it a bit difficult to audit what version of latest are we using, what are your plans on tagging these images?

**Comment by Saghen** [comment]
https://github.com/huggingface/chat-ui/blob/main/.github/workflows/build-image.yml#L73-L75
These ones will only trigger on the [push tag event](https://github.com/docker/metadata-action?tab=readme-ov-file#semver)

**Comment by antonioramos1** [comment]
Closing at it is now solved :)
