### ISSUE TITLE
Community Assistants

### ISSUE THREAD

**Issue by Coinficient** [huggingface/chat-ui#997]
Hi, I've looked through all the possible issues but I didn't find what I was looking for. 

On self-hosted is the option to have the community assistants such as the ones on https://huggingface.co/chat/ not available? I've also noticed that when I create Assistants on my side they do not show up on community tabs either they are purely user restricted, I am missing something? I've configured the hf token and the API base, any hints are appreciated.

![image](https://github.com/huggingface/chat-ui/assets/165610201/f10307a3-17c4-4e0c-9036-1f63237e2f72)

**Comment by flexchar** [comment]
Actually I have been wondering the same ever since they popped up in January. Today I wanted to create the issue and found this. 

The assistants tab is always empty ⤵️
<img width="1108" alt="image" src="https://github.com/huggingface/chat-ui/assets/9198896/09aad689-2b24-4d9a-9e97-118480d33d4e">


even though they all appear in the Settings modal ⤵️
<img width="870" alt="image" src="https://github.com/huggingface/chat-ui/assets/9198896/befa5dfe-2d28-4824-b1e2-ce2df5614696">


Is this by design or is this something huge we're missing?

**Comment by nsarrazin** [comment]
Hey so it is technically by design, since on HuggingChat we manually curate assistants so assistants must have more than 1 user and have `featured: true` in the DB in order to show on the community page.

However this behaviour doesn't make a lot of sense for other chat-ui users, so I moved it behind a feature flag in #1043, let me know if it works for you!
